---
- hosts: all
  become: user
  become_user: labuser
  gather_facts: yes
  tasks:
  - name: Gather the free disk space
    shell: df -h
    register: result
  - name: Display the JSON formatted results
    debug: var=result


